//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EUUI - EURes Extension for EUUIPanelBase
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.U2D;
using Cysharp.Threading.Tasks;
using EUFramework.Extension.EURes;

namespace EUFramework.Extension.EUUI
{
    /// <summary>
    /// EUUIPanelBase 的 EURes 资源加载扩展（静态扩展方法）
    /// </summary>
    public static class EUUIPanelBaseEUResExtensions
    {
        /// <summary>
        /// 设置 Image 图片（从 url 加载，扩展方法）
        /// url 格式：atlasName/spriteName
        /// </summary>
        public static void SetImage<T>(this EUUIPanelBase<T> panel, UnityEngine.UI.Image image, string url, bool? isRemote = null, bool isSetNativeSize = true)
            where T : EUUIPanelBase<T>, new()
        {
            if (image == null || string.IsNullOrEmpty(url)) return;
            var sprite = panel.LoadSprite(url, isRemote);
            if (sprite != null)
            {
                image.sprite = sprite;
                if (isSetNativeSize) image.SetNativeSize();
            }
        }

        /// <summary>
        /// 从 EURes 加载 Sprite（扩展方法）
        /// url 格式：atlasName/spriteName
        /// </summary>
        public static Sprite LoadSprite<T>(this EUUIPanelBase<T> panel, string url, bool? isRemote = null) 
            where T : EUUIPanelBase<T>, new()
        {
            if (string.IsNullOrEmpty(url)) return null;

            int splitIndex = url.IndexOf('/');
            if (splitIndex <= 0 || splitIndex == url.Length - 1)
            {
                Debug.LogWarning($"[EUUI] Sprite url 格式错误: {url}，应为 atlasName/spriteName");
                return null;
            }

            string atlasName = url.Substring(0, splitIndex);
            string spriteName = url.Substring(splitIndex + 1);
            
            var config = EUUIKit.Config;
            bool useRemote = isRemote ?? true;
            string prefix = useRemote ? config.remoteAtlasPath : config.builtinAtlasPath;
            string atlasPath = $"{prefix}/{atlasName}.spriteatlas";

            var package = EUResKit.GetPackage();
            if (package == null)
            {
                Debug.LogError("[EUUI] EUResKit 未初始化或未找到默认包");
                return null;
            }

            var handle = package.LoadAssetSync<SpriteAtlas>(atlasPath);
            var atlas = handle.AssetObject as SpriteAtlas;
            return atlas?.GetSprite(spriteName);
        }

        /// <summary>
        /// 从 EURes 异步加载 Prefab（扩展方法）
        /// </summary>
        public static async UniTask<GameObject> LoadPrefabAsync<T>(this EUUIPanelBase<T> panel, string path) 
            where T : EUUIPanelBase<T>, new()
        {
            if (string.IsNullOrEmpty(path))
            {
                Debug.LogWarning("[EUUI] Prefab path 为空");
                return null;
            }

            var config = EUUIKit.Config;
            bool useRemote = true;
            string prefix = useRemote ? config.remotePrefabPath : config.builtinPrefabPath;
            string fullPath = $"{prefix}/{path}.prefab";

            var package = EUResKit.GetPackage();
            if (package == null)
            {
                Debug.LogError("[EUUI] EUResKit 未初始化或未找到默认包");
                return null;
            }

            var handle = package.LoadAssetAsync<GameObject>(fullPath);
            await handle.ToUniTask();
            return handle.AssetObject as GameObject;
        }

        /// <summary>
        /// 从 EURes 同步加载 Prefab（扩展方法）
        /// </summary>
        public static GameObject LoadPrefab<T>(this EUUIPanelBase<T> panel, string path) 
            where T : EUUIPanelBase<T>, new()
        {
            if (string.IsNullOrEmpty(path))
            {
                Debug.LogWarning("[EUUI] Prefab path 为空");
                return null;
            }

            var config = EUUIKit.Config;
            bool useRemote = true;
            string prefix = useRemote ? config.remotePrefabPath : config.builtinPrefabPath;
            string fullPath = $"{prefix}/{path}.prefab";

            var package = EUResKit.GetPackage();
            if (package == null)
            {
                Debug.LogError("[EUUI] EUResKit 未初始化或未找到默认包");
                return null;
            }

            var handle = package.LoadAssetSync<GameObject>(fullPath);
            return handle.AssetObject as GameObject;
        }
    }
}
